# This triggers on all merged PRs into main

name: Main - TF Apply

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev:
    if: ${{ github.event.pull_request.merged == true }}
    name: "[DEV] ${{ matrix.directory }} - ${{ matrix.region }}"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-plan-apply.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: '.'
      just-plan: false
    secrets: inherit
