# NOTE: Hopefully this can be improved if GitHub Actions ever supports multi-choice inputs, to best utilize matrix builds.

name: Manual Trigger - Single Target

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the target environment'
        type: choice
        required: true
        options:
        - dev
      region:
        description: 'Select the target environment'
        type: choice
        required: true
        options:
        - eu-central-1
      plan-instead-of-apply:
        description: 'Run terraform "plan" instead of "apply"'
        type: boolean
        default: true

permissions:
  id-token: write
  pull-requests: write
  contents: read
  
jobs:
  main:
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-plan-apply.yml@main
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      working-directory: '.'
      just-plan: ${{ inputs.plan-instead-of-apply }}
    secrets: inherit
