# NOTE: Hopefully this can be improved if GitHub Actions ever supports multi-choice inputs, to best utilize matrix builds.

name: Manual Trigger - Single Target

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the target environment'
        type: choice
        required: true
        options:
        - dev
        # - stg
        # - prod
      region:
        description: 'Select the target environment'
        type: choice
        required: true
        options:
        # - us-west-2
        # - us-east-1
        # - us-west-1
        - eu-central-1
        # - eu-west-1
        # - ap-southeast-2
      plan-instead-of-apply:
        description: 'Run terraform "plan" instead of "apply"'
        type: boolean
        default: true

# permissions:
#   id-token: write
#   contents: write
#   pull-requests: write
  
jobs:
  main:
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-plan-apply.yml@main
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      working-directory: '.'
      just-plan: ${{ inputs.plan-instead-of-apply }}
    secrets: inherit
